---
apiVersion: projectriff.io/v1alpha1
kind: Invoker
metadata:
  name: java-gradle
spec:
  version: 0.0.8-snapshot
  matchers:
  - "pom.xml"
  handler:
    default: "functions.{{ .TitleCase .FunctionName }}"
    description: the fully qualified class name or bean name of the function handler
  functionTemplate:
    spec:
      protocol: http
  files:
  - path: Dockerfile
    template: |
      FROM keeganwitt/docker-gradle-root:4.6.0-jdk8-alpine as build
      COPY ./*.* /home/gradle/fun/
      COPY ./src /home/gradle/fun/src
      WORKDIR /home/gradle/fun
      ENV GRADLE_USER_HOME=~/.gradle
      RUN gradle build --no-daemon -x test
      FROM projectriff/java-function-invoker:0.0.7
      ARG FUNCTION_JAR=/functions/function.jar
      ARG FUNCTION_HANDLER={{.Handler}}
      COPY --from=build home/gradle/fun/build/libs/*.jar $FUNCTION_JAR
      ENV FUNCTION_URI file://${FUNCTION_JAR}?handler=${FUNCTION_HANDLER}
