---
apiVersion: projectriff.io/v1alpha1
kind: Invoker
metadata:
  name: java-gradle
spec:
  version: 0.0.8-snapshot
  matchers:
  - "build.gradle"
  handler:
    default: "functions.{{ .TitleCase .FunctionName }}"
    description: the fully qualified class name or bean name of the function handler
  functionTemplate:
    spec:
      protocol: http
  files:
  - path: Dockerfile
    template: |
      FROM gradle:4.9.0-jdk8 as build
      COPY --chown=gradle:gradle *.gradle gradle.* /home/gradle/
      COPY --chown=gradle:gradle src /home/gradle/src
      USER gradle
      WORKDIR /home/gradle
      ENV GRADLE_USER_HOME=/home/gradle/.gradle
      RUN gradle build --no-daemon -q -x test
      FROM projectriff/java-function-invoker:{{.InvokerVersion}}
      ARG FUNCTION_JAR=/functions/function.jar
      ARG FUNCTION_HANDLER={{.Handler}}
      COPY --from=build home/gradle/build/libs/*.jar $FUNCTION_JAR
      ENV FUNCTION_URI file://${FUNCTION_JAR}?handler=${FUNCTION_HANDLER}
