---
apiVersion: projectriff.io/v1alpha1
kind: Invoker
metadata:
  name: java-mvn
spec:
  version: 0.0.8-snapshot
  matchers:
  - "pom.xml"
  handler:
    default: "functions.{{ .TitleCase .FunctionName }}"
    description: the fully qualified class name or bean name of the function handler
  functionTemplate:
    spec:
      protocol: http
  files:
  - path: Dockerfile
    template: |
      FROM maven:3.5-jdk-8-alpine as build
      ADD pom.xml ./pom.xml
      ADD src ./src
      RUN mvn package -B -q -DskipTests
      FROM projectriff/java-function-invoker:{{.InvokerVersion}}
      ARG FUNCTION_JAR=/functions/function.jar
      ARG FUNCTION_HANDLER={{.Handler}}
      COPY --from=build target/*.jar $FUNCTION_JAR
      ENV FUNCTION_URI file://${FUNCTION_JAR}?handler=${FUNCTION_HANDLER}
